---
- name: Create GCP Instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    auth_kind: "{{lookup('env','GCP_AUTH_KIND')}}"
    credentials_file: "{{lookup('env','GCP_SERVICE_ACCOUNT_FILE')}}"
    project_id: "{{lookup('env','GCP_PROJECT')}}"
    vpc_name: "default"
    instance_count: 2 #instances to create
    instance_name: "test"
    instance_type: "n1-standard-1"
    region: "us-central1"
    zone: "a"
    disk_name: "disk-instance"
    storage_size: 100
    source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts"
    address_name: address-instance
    key_loc: "~/.ssh/id_rsa.pub" #key locations
    username: "" #server username
  pre_tasks:
    - name: fetch VPC details
      gcp_compute_network_info:
        filters:
          - name = "{{vpc_name}}"
        project: "{{project_id}}"
        auth_kind: "{{auth_kind}}"
        service_account_file: "{{credentials_file}}"
      register: network    
  roles:
    - Instance
  post_tasks:

